### ISSUE TITLE
I didn't set a backup location in the path file, where are the files?

### ISSUE THREAD

**Issue by RicardoPedroCampos** [gcapes/file-backups-rfields#11]
Not sure where files are being saved. Can we put the archived path in the logsheet?

Didn't set a backup directory, maybe this was my issue.

**Comment by gcapes** [comment]
Hmm, this is strange. If I don't set a back up directory in the path file, I get an assertion error.
The source and back up directory are both already recorded in the log sheet (backuplog.txt). Let me know if you can reproduce this error.
