### ISSUE TITLE
Backup- after backup complete prompt to create missing log sheets

### ISSUE THREAD

**Issue by RicardoPedroCampos** [gcapes/file-backups-rfields#18]

**Comment by gcapes** [comment]
I wonder if this is a bit of a circular idea? We could equally prompt to do the back up after creating the logsheets.

**Comment by RicardoPedroCampos** [comment]
Yeah you are right. Prompt after the creation of log sheets.

**Comment by gcapes** [comment]
:) I was actually arguing to keep each step manual, but I guess there is no reason to delay backing up once the logsheets have been created. The converse is not true -- the logsheets may not be at hand. I'll add a prompt to back up after creating logsheets.
